version: "3.8"
services:
  lung-cancer-detector-app:
    build:
      context: ./lung-cancer-detector-app
      dockerfile: Dockerfile
    container_name: lung-cancer-detector-app
    ports:
      - "4200:4200"
    depends_on:
      - auth
      - models
      - history
      - email

  auth:
    build:
      context: ./auth
      dockerfile: Dockerfile
    container_name: auth
    ports:
      - "3100:3100"
    environment:
      POSTGRES_HOST: postgres-db
      POSTGRES_DB: lung-cancer-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    depends_on:
      - postgres-db

  models:
    build:
      context: ./models
      dockerfile: Dockerfile
    container_name: models
    ports:
      - "3000:3000"

  history:
    build:
      context: ./history
      dockerfile: Dockerfile
    container_name: history
    ports:
      - "3050:3050"
    environment:
      POSTGRES_HOST: postgres-db
      POSTGRES_DB: lung-cancer-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    depends_on:
      - postgres-db

  email:
    build:
      context: ./email
      dockerfile: Dockerfile
    container_name: email
    ports:
      - "3200:3200"
    environment:
      MAIL_SERVER: 'smtp.gmail.com'
      MAIL_PORT: 587
      MAIL_USERNAME: 'lungcancerdetector@gmail.com'
      MAIL_PASSWORD: 'ebvx pcdf bksy dmsf'
      MAIL_USE_TLS: 'true'
      MAIL_USE_SSL: 'false'

  postgres-db:
    image: postgres:15
    container_name: postgres-db
    ports:
      - "5123:5432"
    environment:
      POSTGRES_DB: lung-cancer-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres-db:/var/lib/postgresql/data
      - ./database/init-database.sql:/docker-entrypoint-initdb.d/init-database.sql

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    ports:
      - "80:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    depends_on:
      - postgres-db

volumes:
  postgres-db:
